apiVersion: v1
kind: Service
metadata:
  name: egress
  labels:
    app: egress
spec:
  selector:
    app: egress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443