apiVersion: v1
kind: Service
metadata:
    labels:
        app: ingress-upstream
    name: ingress-upstream
    namespace: default
spec:
    ports:
    - name: 80-nova
      port: 80
      protocol: TCP
      targetPort: 1080
    selector:
        app: nova-client
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}